### ISSUE TITLE
`python -m mautrix_signal` not writing the port given in `config.yaml` to registration file

### ISSUE THREAD

**Issue by a000a** [tulir/mautrix-signal#95]
`python -m mautrix_signal` writes the default port to  `registration.yaml` and not the port given in `config.yaml`.

**Comment by tulir** [comment]
Seems to work fine for me (address from config is copied to registration)

**Comment by a000a** [comment]
haven't seen there are two ports in the config file. the `address` is the one being used for `registration.yaml`.

```
# Changing these values requires regeneration of the registration.
  appservice:                                                                     
     # The address that the homeserver can use to connect to this appservice.
     address: http://localhost:29328
     # When using https:// the TLS certificate and key files for the address.    
     tls_cert: false
     tls_key: false
                                                                                 
     # The hostname and port where this appservice should listen.                
     hostname: 0.0.0.0
     port: 29338
```
